apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomee-app
  template:
    metadata:
      labels:
        app: tomee-app
    spec:
      containers:
      - name: tomee-container
        image: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
  - name: http
    targetPort: 80
    port: 8080
  selector:
    app: tomee-app
  type: LoadBalancer
